name: Run and Commit on Changes

on:
  push:
    paths:
      - 'README.md'
      - 'scripts/main.go'

jobs:
  execute-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run main.go
        run: |
          cd scripts
          go run main.go
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update index.html'
